# Generated by Django 5.0.4 on 2024-04-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=14)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
