# Generated by Django 5.0.4 on 2024-05-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_professor'),
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aluno', verbose_name='treino')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treino', to='cadastro.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.exercicio', verbose_name='item_treino')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.treino', verbose_name='item_treino')),
            ],
        ),
    ]
